// Mocks generated by Mockito 5.4.6 from annotations
// in passpal/test/core/network/interceptors/error_interceptor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:passpal/core/error/logging/app_logger.dart' as _i4;
import 'package:passpal/core/error/models/app_error.dart' as _i5;
import 'package:passpal/core/error/notifiers/error_notifier.dart' as _i6;
import 'package:passpal/core/error/notifiers/error_state.dart' as _i3;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.AutoDisposeNotifierProviderRef<T> {
  _FakeAutoDisposeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeErrorState_1 extends _i1.SmartFake implements _i3.ErrorState {
  _FakeErrorState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i4.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void debug(
    String? message, {
    Map<String, dynamic>? attributes,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #debug,
      [message],
      {#attributes: attributes, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void info(
    String? message, {
    Map<String, dynamic>? attributes,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #info,
      [message],
      {#attributes: attributes, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void warning(
    String? message, {
    Map<String, dynamic>? attributes,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #warning,
      [message],
      {#attributes: attributes, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void error(
    String? message, {
    Map<String, dynamic>? attributes,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#attributes: attributes, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void fatal(
    String? message, {
    Map<String, dynamic>? attributes,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #fatal,
      [message],
      {#attributes: attributes, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void logError(
    _i5.AppError? error, {
    Map<String, dynamic>? additionalAttributes,
  }) => super.noSuchMethod(
    Invocation.method(
      #logError,
      [error],
      {#additionalAttributes: additionalAttributes},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ErrorNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorNotifier extends _i1.Mock implements _i6.ErrorNotifier {
  MockErrorNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AutoDisposeNotifierProviderRef<_i3.ErrorState> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeAutoDisposeNotifierProviderRef_0<_i3.ErrorState>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i2.AutoDisposeNotifierProviderRef<_i3.ErrorState>);

  @override
  _i3.ErrorState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeErrorState_1(this, Invocation.getter(#state)),
          )
          as _i3.ErrorState);

  @override
  set state(_i3.ErrorState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.ErrorState build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeErrorState_1(this, Invocation.method(#build, [])),
          )
          as _i3.ErrorState);

  @override
  _i7.Future<void> handleError(
    _i5.AppError? error, {
    bool? showToUser = true,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #handleError,
              [error],
              {#showToUser: showToUser, #context: context},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void dismissError(String? errorCode) => super.noSuchMethod(
    Invocation.method(#dismissError, [errorCode]),
    returnValueForMissingStub: null,
  );

  @override
  void clearDismissedErrors() => super.noSuchMethod(
    Invocation.method(#clearDismissedErrors, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearAllErrors() => super.noSuchMethod(
    Invocation.method(#clearAllErrors, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearErrorsOfType(Type? errorType) => super.noSuchMethod(
    Invocation.method(#clearErrorsOfType, [errorType]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> reportNetworkError({
    required String? message,
    String? errorCode,
    StackTrace? stackTrace,
    bool? canRetry = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportNetworkError, [], {
              #message: message,
              #errorCode: errorCode,
              #stackTrace: stackTrace,
              #canRetry: canRetry,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reportAuthenticationError({
    required String? message,
    String? errorCode,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportAuthenticationError, [], {
              #message: message,
              #errorCode: errorCode,
              #stackTrace: stackTrace,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reportStorageError({
    required String? message,
    String? errorCode,
    StackTrace? stackTrace,
    bool? canRetry = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportStorageError, [], {
              #message: message,
              #errorCode: errorCode,
              #stackTrace: stackTrace,
              #canRetry: canRetry,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reportConfigError({
    required String? message,
    String? errorCode,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportConfigError, [], {
              #message: message,
              #errorCode: errorCode,
              #stackTrace: stackTrace,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reportConfigSourceError({
    required String? message,
    String? errorCode,
    StackTrace? stackTrace,
    bool? canRetry = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportConfigSourceError, [], {
              #message: message,
              #errorCode: errorCode,
              #stackTrace: stackTrace,
              #canRetry: canRetry,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reportConfigParseError({
    required String? message,
    String? errorCode,
    StackTrace? stackTrace,
    bool? canRetry = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportConfigParseError, [], {
              #message: message,
              #errorCode: errorCode,
              #stackTrace: stackTrace,
              #canRetry: canRetry,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void listenSelf(
    void Function(_i3.ErrorState?, _i3.ErrorState)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(_i3.ErrorState? previous, _i3.ErrorState? next) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}
