name: passpal
description: "Chukyo University student app"
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter
    hooks_riverpod: ^2.6.1
    flutter_hooks: ^0.21.2
    riverpod_annotation: ^2.6.1
    firebase_core: ^4.0.0
    firebase_auth: ^6.0.0
    firebase_remote_config: ^6.0.0
    firebase_in_app_messaging: ^0.9.0
    firebase_messaging: ^16.0.0
    firebase_crashlytics: ^5.0.0
    firebase_analytics: ^12.0.0
    google_sign_in: ^7.1.1
    google_fonts: ^6.2.1
    freezed_annotation: ^3.1.0
    json_annotation: ^4.9.0
    dio: ^5.8.0+1
    cookie_jar: ^4.0.8
    html: ^0.15.6
    flutter_secure_storage: ^9.2.4
    shared_preferences: ^2.5.3
    version: ^3.0.2
    permission_handler: ^12.0.1
    go_router: ^16.0.0
    drift: ^2.28.0
    drift_flutter: ^0.2.5
    path_provider: ^2.1.5
    flutter_launcher_icons: ^0.14.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    riverpod_generator: ^2.6.5
    riverpod_lint: ^2.6.5
    build_runner: any
    custom_lint: any
    freezed: ^3.0.6
    json_serializable: ^6.9.5
    drift_dev: ^2.28.0

flutter:
    uses-material-design: true

flutter_icons:
  ios: true
  image_path: "assets/images/launcher/icon_ios.png"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "assets/images/launcher/icon_adaptive_background.png"
  adaptive_icon_foreground: "assets/images/launcher/icon_adaptive_foreground.png"
