// Mocks generated by Mockito 5.4.6 from annotations
// in passpal/test/core/error/exception_propagation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:passpal/core/error/app_exception.dart' as _i5;
import 'package:passpal/core/error/crashlytics_reporter.dart' as _i3;
import 'package:passpal/core/error/error_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CrashlyticsReporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashlyticsReporter extends _i1.Mock
    implements _i3.CrashlyticsReporter {
  @override
  _i4.Future<void> recordError(_i5.AppException? exception) =>
      (super.noSuchMethod(
            Invocation.method(#recordError, [exception]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserContext({
    String? userId,
    String? email,
    Map<String, String>? customKeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserContext, [], {
              #userId: userId,
              #email: email,
              #customKeys: customKeys,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ErrorNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorNotifier extends _i1.Mock implements _i6.ErrorNotifier {
  @override
  bool get isShowing =>
      (super.noSuchMethod(
            Invocation.getter(#isShowing),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.NotifierProviderRef<_i6.AppErrorState> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeNotifierProviderRef_0<_i6.AppErrorState>(
              this,
              Invocation.getter(#ref),
            ),
            returnValueForMissingStub:
                _FakeNotifierProviderRef_0<_i6.AppErrorState>(
                  this,
                  Invocation.getter(#ref),
                ),
          )
          as _i2.NotifierProviderRef<_i6.AppErrorState>);

  @override
  _i6.AppErrorState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i7.dummyValue<_i6.AppErrorState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _i7.dummyValue<_i6.AppErrorState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i6.AppErrorState);

  @override
  set state(_i6.AppErrorState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.AppErrorState build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _i7.dummyValue<_i6.AppErrorState>(
              this,
              Invocation.method(#build, []),
            ),
            returnValueForMissingStub: _i7.dummyValue<_i6.AppErrorState>(
              this,
              Invocation.method(#build, []),
            ),
          )
          as _i6.AppErrorState);

  @override
  _i4.Future<void> show(
    _i5.AppException? exception, {
    bool? recordToCrashlytics = true,
    bool? autoDismiss = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #show,
              [exception],
              {
                #recordToCrashlytics: recordToCrashlytics,
                #autoDismiss: autoDismiss,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dismiss() => super.noSuchMethod(
    Invocation.method(#dismiss, []),
    returnValueForMissingStub: null,
  );

  @override
  void listenSelf(
    void Function(_i6.AppErrorState?, _i6.AppErrorState)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(
    _i6.AppErrorState? previous,
    _i6.AppErrorState? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
