// Mocks generated by Mockito 5.4.6 from annotations
// in passpal/test/core/storage/services/migration_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:passpal/core/error/models/failure.dart' as _i5;
import 'package:passpal/core/storage/interfaces/cache_storage_interface.dart'
    as _i6;
import 'package:passpal/core/storage/interfaces/preference_storage_interface.dart'
    as _i8;
import 'package:passpal/core/storage/interfaces/secure_storage_interface.dart'
    as _i3;
import 'package:passpal/core/storage/models/cache_entry.dart' as _i7;
import 'package:passpal/core/storage/models/preference_types.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SecureStorageInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageInterface extends _i1.Mock
    implements _i3.SecureStorageInterface {
  MockSecureStorageInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String?>> read(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [key]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String?>>.value(
              _FakeEither_0<_i5.Failure, String?>(
                this,
                Invocation.method(#read, [key]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> write(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#write, [key, value]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#write, [key, value]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#delete, [key]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#containsKey, [key]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#clear, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getAllKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getAllKeys, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
                  _FakeEither_0<_i5.Failure, List<String>>(
                    this,
                    Invocation.method(#getAllKeys, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);
}

/// A class which mocks [CacheStorageInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheStorageInterface extends _i1.Mock
    implements _i6.CacheStorageInterface {
  MockCacheStorageInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i6.CacheEvent> get changes =>
      (super.noSuchMethod(
            Invocation.getter(#changes),
            returnValue: _i4.Stream<_i6.CacheEvent>.empty(),
          )
          as _i4.Stream<_i6.CacheEvent>);

  @override
  _i4.Stream<_i6.CacheValueEvent> get valueChanges =>
      (super.noSuchMethod(
            Invocation.getter(#valueChanges),
            returnValue: _i4.Stream<_i6.CacheValueEvent>.empty(),
          )
          as _i4.Stream<_i6.CacheValueEvent>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>>> get<T>(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>>>.value(
                  _FakeEither_0<_i5.Failure, _i7.CacheEntry<T>>(
                    this,
                    Invocation.method(#get, [key]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> set<T>(
    String? key,
    T? value, {
    Duration? ttl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#set, [key, value], {#ttl: ttl}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#set, [key, value], {#ttl: ttl}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#delete, [key]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#containsKey, [key]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#clear, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CacheStats>> getStats() =>
      (super.noSuchMethod(
            Invocation.method(#getStats, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.CacheStats>>.value(
                  _FakeEither_0<_i5.Failure, _i6.CacheStats>(
                    this,
                    Invocation.method(#getStats, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.CacheStats>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> cleanup() =>
      (super.noSuchMethod(
            Invocation.method(#cleanup, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#cleanup, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Stream<_i7.CacheEntry<T>?> watchKey<T>(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#watchKey, [key]),
            returnValue: _i4.Stream<_i7.CacheEntry<T>?>.empty(),
          )
          as _i4.Stream<_i7.CacheEntry<T>?>);

  @override
  _i4.Stream<Map<String, _i7.CacheEntry<dynamic>?>> watchKeys(
    List<String>? keys,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchKeys, [keys]),
            returnValue:
                _i4.Stream<Map<String, _i7.CacheEntry<dynamic>?>>.empty(),
          )
          as _i4.Stream<Map<String, _i7.CacheEntry<dynamic>?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>?>> getStale<T>(
    String? key,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getStale, [key]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>?>>.value(
                  _FakeEither_0<_i5.Failure, _i7.CacheEntry<T>?>(
                    this,
                    Invocation.method(#getStale, [key]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>?>> swr<T>(
    String? key,
    _i4.Future<T> Function()? revalidate, {
    Duration? ttl,
    bool? forceRevalidate = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #swr,
              [key, revalidate],
              {#ttl: ttl, #forceRevalidate: forceRevalidate},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>?>>.value(
                  _FakeEither_0<_i5.Failure, _i7.CacheEntry<T>?>(
                    this,
                    Invocation.method(
                      #swr,
                      [key, revalidate],
                      {#ttl: ttl, #forceRevalidate: forceRevalidate},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>>> swrWithFallback<T>(
    String? key,
    _i4.Future<T> Function()? revalidate, {
    Duration? ttl,
    bool? forceRevalidate = false,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #swrWithFallback,
              [key, revalidate],
              {#ttl: ttl, #forceRevalidate: forceRevalidate, #timeout: timeout},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>>>.value(
                  _FakeEither_0<_i5.Failure, _i7.CacheEntry<T>>(
                    this,
                    Invocation.method(
                      #swrWithFallback,
                      [key, revalidate],
                      {
                        #ttl: ttl,
                        #forceRevalidate: forceRevalidate,
                        #timeout: timeout,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.CacheEntry<T>>>);
}

/// A class which mocks [PreferenceStorageInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferenceStorageInterface extends _i1.Mock
    implements _i8.PreferenceStorageInterface {
  MockPreferenceStorageInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i8.PreferenceEvent> get changes =>
      (super.noSuchMethod(
            Invocation.getter(#changes),
            returnValue: _i4.Stream<_i8.PreferenceEvent>.empty(),
          )
          as _i4.Stream<_i8.PreferenceEvent>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T?>> get<T>(_i9.PreferenceKey<T>? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, T?>>.value(
              _FakeEither_0<_i5.Failure, T?>(
                this,
                Invocation.method(#get, [key]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, T?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> set<T>(
    _i9.PreferenceKey<T>? key,
    T? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#set, [key, value]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#set, [key, value]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> delete<T>(
    _i9.PreferenceKey<T>? key,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#delete, [key]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> containsKey<T>(
    _i9.PreferenceKey<T>? key,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#containsKey, [key]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#clear, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getAllKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getAllKeys, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
                  _FakeEither_0<_i5.Failure, List<String>>(
                    this,
                    Invocation.method(#getAllKeys, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Stream<T?> watch<T>(_i9.PreferenceKey<T>? key) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [key]),
            returnValue: _i4.Stream<T?>.empty(),
          )
          as _i4.Stream<T?>);
}
