// Mocks generated by Mockito 5.4.6 from annotations
// in passpal/test/core/config/services/config_update_monitor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:firebase_remote_config/firebase_remote_config.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:passpal/core/config/models/app_config.dart' as _i3;
import 'package:passpal/core/config/sources/remote_config_source.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseRemoteConfig_0 extends _i1.SmartFake
    implements _i2.FirebaseRemoteConfig {
  _FakeFirebaseRemoteConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppConfig_1 extends _i1.SmartFake implements _i3.AppConfig {
  _FakeAppConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RemoteConfigSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigSource extends _i1.Mock
    implements _i4.RemoteConfigSource {
  MockRemoteConfigSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.RemoteConfigUpdate> get onConfigUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#onConfigUpdated),
            returnValue: _i5.Stream<_i2.RemoteConfigUpdate>.empty(),
          )
          as _i5.Stream<_i2.RemoteConfigUpdate>);

  @override
  _i2.FirebaseRemoteConfig get instance =>
      (super.noSuchMethod(
            Invocation.getter(#instance),
            returnValue: _FakeFirebaseRemoteConfig_0(
              this,
              Invocation.getter(#instance),
            ),
          )
          as _i2.FirebaseRemoteConfig);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.AppConfig> loadConfig({
    Duration? fetchTimeout,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadConfig, [], {
              #fetchTimeout: fetchTimeout,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i5.Future<_i3.AppConfig>.value(
              _FakeAppConfig_1(
                this,
                Invocation.method(#loadConfig, [], {
                  #fetchTimeout: fetchTimeout,
                  #forceRefresh: forceRefresh,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AppConfig>);

  @override
  _i5.Future<bool> hasConfig() =>
      (super.noSuchMethod(
            Invocation.method(#hasConfig, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  T? getValue<T>(String? key) =>
      (super.noSuchMethod(Invocation.method(#getValue, [key])) as T?);

  @override
  Map<String, dynamic>? getJsonValue(String? key) =>
      (super.noSuchMethod(Invocation.method(#getJsonValue, [key]))
          as Map<String, dynamic>?);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );
}
