// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcjeCMJfDVPxBTLKx_edx_cNJYcIHoFyw',
    appId: '1:781950936841:android:f41091715a533f5a1915d8',
    messagingSenderId: '781950936841',
    projectId: 'passpal-c55ac',
    databaseURL: 'https://passpal-c55ac-default-rtdb.firebaseio.com',
    storageBucket: 'passpal-c55ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDplHkzwdepJ8ZjLWZwg5IgKn3gpH4HDhI',
    appId: '1:781950936841:ios:5a7b989a6dd478e51915d8',
    messagingSenderId: '781950936841',
    projectId: 'passpal-c55ac',
    databaseURL: 'https://passpal-c55ac-default-rtdb.firebaseio.com',
    storageBucket: 'passpal-c55ac.firebasestorage.app',
    iosBundleId: 'app.chukyo-passpal.passpal',
  );

}