// Mocks generated by Mockito 5.4.6 from annotations
// in passpal/test/core/config/providers/config_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:passpal/core/config/models/app_config.dart' as _i2;
import 'package:passpal/core/config/services/config_cache.dart' as _i5;
import 'package:passpal/core/config/services/config_merger.dart' as _i3;
import 'package:passpal/core/error/logging/log_level.dart' as _i8;
import 'package:passpal/core/error/models/app_error.dart' as _i7;
import 'package:passpal/core/error/services/crashlytics_service.dart' as _i6;
import 'package:passpal/core/error/services/error_reporter.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppConfig_0 extends _i1.SmartFake implements _i2.AppConfig {
  _FakeAppConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConfigMerger].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigMerger extends _i1.Mock implements _i3.ConfigMerger {
  @override
  _i4.Future<_i2.AppConfig> mergeConfigs() =>
      (super.noSuchMethod(
            Invocation.method(#mergeConfigs, []),
            returnValue: _i4.Future<_i2.AppConfig>.value(
              _FakeAppConfig_0(this, Invocation.method(#mergeConfigs, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.AppConfig>.value(
              _FakeAppConfig_0(this, Invocation.method(#mergeConfigs, [])),
            ),
          )
          as _i4.Future<_i2.AppConfig>);
}

/// A class which mocks [ConfigCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigCache extends _i1.Mock implements _i5.ConfigCache {
  @override
  bool get isCacheValid =>
      (super.noSuchMethod(
            Invocation.getter(#isCacheValid),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Stream<_i2.AppConfig?> get cacheUpdateStream =>
      (super.noSuchMethod(
            Invocation.getter(#cacheUpdateStream),
            returnValue: _i4.Stream<_i2.AppConfig?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i2.AppConfig?>.empty(),
          )
          as _i4.Stream<_i2.AppConfig?>);

  @override
  void cacheConfig(_i2.AppConfig? config) => super.noSuchMethod(
    Invocation.method(#cacheConfig, [config]),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateCache() => super.noSuchMethod(
    Invocation.method(#invalidateCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void setCacheTime(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setCacheTime, [time]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CrashlyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashlyticsService extends _i1.Mock
    implements _i6.CrashlyticsService {
  @override
  _i4.Future<void> recordError(
    _i7.AppError? error, {
    Map<String, dynamic>? additionalAttributes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordError,
              [error],
              {#additionalAttributes: additionalAttributes},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordLog(
    _i8.LogLevel? level,
    String? message, {
    Map<String, dynamic>? attributes,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordLog,
              [level, message],
              {#attributes: attributes, #stackTrace: stackTrace},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordException(
    Object? exception,
    StackTrace? stackTrace, {
    bool? fatal = false,
    Map<String, dynamic>? attributes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordException,
              [exception, stackTrace],
              {#fatal: fatal, #attributes: attributes},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCustomKey(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomKey, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCustomKeys() =>
      (super.noSuchMethod(
            Invocation.method(#clearCustomKeys, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ErrorReporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorReporter extends _i1.Mock implements _i9.ErrorReporter {
  @override
  _i4.Future<void> reportError(
    _i7.AppError? error, {
    Map<String, dynamic>? additionalAttributes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #reportError,
              [error],
              {#additionalAttributes: additionalAttributes},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reportLog(
    _i8.LogLevel? level,
    String? message, {
    Map<String, dynamic>? attributes,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #reportLog,
              [level, message],
              {#attributes: attributes, #stackTrace: stackTrace},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reportException(
    Object? exception,
    StackTrace? stackTrace, {
    bool? fatal = false,
    Map<String, dynamic>? attributes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #reportException,
              [exception, stackTrace],
              {#fatal: fatal, #attributes: attributes},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCustomKey(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomKey, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCustomKeys() =>
      (super.noSuchMethod(
            Invocation.method(#clearCustomKeys, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
